<?php
/**
 * Manifest Importer
 *
 * Handles upload and processing of Seedcast content manifest zips on the
 * New Sermon screen. Populates sermon fields from the manifest and HTML files.
 *
 * This is the same import contract the AI pipeline will use internally
 * the API generates a manifest zip and this class processes it.
 *
 * @package SeedcastSermonLibrary
 */

namespace SeedcastSermonLibrary\Admin;

use SeedcastSermonLibrary\Import\FieldMap;

if ( ! defined( 'ABSPATH' ) ) exit;

class ManifestImporter {

	public function init(): void {
		add_action( 'add_meta_boxes',         [ $this, 'register_meta_box' ] );
		add_action( 'wp_ajax_scsl_import_manifest', [ $this, 'handle_upload' ] );
	}

	public function register_meta_box(): void {
		// This box is for churches that generate content on seedcast.ai and
		// bring the zip across by hand. With the engine installed and working,
		// the same content arrives on the sermon itself, and offering a second
		// way to do it is just something else to explain.
		if ( defined( 'SCPRO_VERSION' ) && apply_filters( 'scsl_show_manifest_import', false ) === false ) return;

		add_meta_box(
			'scsl_manifest_import',
			__( 'Import Content from Seedcast', 'seedcast-sermon-library' ),
			[ $this, 'render_meta_box' ],
			'scsl_sermon',
			'side',
			'high'
		);
	}

	public function render_meta_box( \WP_Post $post ): void {
		wp_nonce_field( 'scsl_import_manifest_' . $post->ID, 'scsl_manifest_nonce' );
		?>
		<div class="scsl-manifest-import" id="scsl-manifest-import">

			<p class="description">
				<?php esc_html_e( 'Upload a Seedcast content zip to populate this sermon\'s fields automatically. Generated by api.seedcast.ai.', 'seedcast-sermon-library' ); ?>
			</p>

			<div class="scsl-manifest-drop-area" id="scsl-manifest-drop-area">
				<input type="file"
					   id="scsl_manifest_file"
					   name="scsl_manifest_file"
					   accept=".zip"
					   style="display:none" />
				<label for="scsl_manifest_file" class="scsl-manifest-drop-label">
					<span class="scsl-manifest-drop-icon">📦</span>
					<span class="scsl-manifest-drop-text">
						<?php esc_html_e( 'Drop a content zip here or click to choose', 'seedcast-sermon-library' ); ?>
					</span>
				</label>
			</div>

			<div id="scsl-manifest-preview" style="display:none">
				<div class="scsl-manifest-preview-header">
					<strong id="scsl-manifest-title"></strong>
					<span id="scsl-manifest-scripture" class="scsl-manifest-badge"></span>
					<span id="scsl-manifest-speaker" class="scsl-manifest-badge scsl-manifest-badge--speaker"></span>
				</div>
				<ul id="scsl-manifest-items" class="scsl-manifest-item-list"></ul>
				<div class="scsl-manifest-actions">
					<label>
						<input type="checkbox" id="scsl-manifest-overwrite" />
						<?php esc_html_e( 'Overwrite fields that already have content', 'seedcast-sermon-library' ); ?>
					</label>
					<button type="button" class="button button-primary" id="scsl-manifest-import-btn">
						<?php esc_html_e( 'Import Content', 'seedcast-sermon-library' ); ?>
					</button>
					<button type="button" class="button" id="scsl-manifest-cancel-btn">
						<?php esc_html_e( 'Cancel', 'seedcast-sermon-library' ); ?>
					</button>
				</div>
			</div>

			<div id="scsl-manifest-result" style="display:none"></div>

		</div>

		<style>
		.scsl-manifest-drop-area {
			border: 2px dashed #c3c4c7;
			border-radius: 4px;
			padding: 24px;
			text-align: center;
			cursor: pointer;
			transition: border-color .2s, background .2s;
			margin: 8px 0 12px;
		}
		.scsl-manifest-drop-area:hover,
		.scsl-manifest-drop-area.scsl-drag-over {
			border-color: #2271b1;
			background: #f0f6fc;
		}
		.scsl-manifest-drop-icon { font-size: 2rem; display: block; margin-bottom: 6px; }
		.scsl-manifest-drop-label { cursor: pointer; display: block; }
		.scsl-manifest-drop-text { color: #646970; font-size: 13px; }
		.scsl-manifest-preview-header { margin: 12px 0 8px; display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
		.scsl-manifest-badge {
			font-size: 11px; background: #f0f6fc; border: 1px solid #c3c4c7;
			border-radius: 3px; padding: 2px 7px; color: #2271b1;
		}
		.scsl-manifest-badge--speaker { color: #1d2327; background: #f6f7f7; }
		.scsl-manifest-item-list { margin: 0 0 12px; padding: 0; list-style: none; }
		.scsl-manifest-item-list li {
			display: flex; align-items: center; gap: 8px; padding: 4px 0;
			border-bottom: 1px solid #f0f0f0; font-size: 13px;
		}
		.scsl-manifest-item-list li:last-child { border-bottom: none; }
		.scsl-manifest-item-list input[type=checkbox] { margin: 0; }
		.scsl-manifest-actions { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; margin-top: 12px; }
		.scsl-manifest-actions label { margin-right: auto; font-size: 12px; color: #646970; }
		#scsl-manifest-result .notice { margin: 8px 0 0; }
		</style>

		<script>
		jQuery( function( $ ) {

			var $area    = $( '#scsl-manifest-drop-area' );
			var $input   = $( '#scsl_manifest_file' );
			var $preview = $( '#scsl-manifest-preview' );
			var $result  = $( '#scsl-manifest-result' );
			var postId   = <?php echo absint( $post->ID ); ?>;
			var nonce    = <?php echo wp_json_encode( wp_create_nonce( 'scsl_import_manifest_' . $post->ID ) ); ?>;
			var zipFile  = null;
			var manifest = null;

			// Drag and drop
			$area.on( 'dragover dragenter', function( e ) {
				e.preventDefault();
				$area.addClass( 'scsl-drag-over' );
			} ).on( 'dragleave drop', function( e ) {
				e.preventDefault();
				$area.removeClass( 'scsl-drag-over' );
				if ( e.type === 'drop' ) {
					var file = e.originalEvent.dataTransfer.files[0];
					if ( file ) handleFile( file );
				}
			} );

			$input.on( 'change', function() {
				if ( this.files[0] ) handleFile( this.files[0] );
			} );

			function handleFile( file ) {
				if ( ! file.name.match( /\.zip$/i ) ) {
					showResult( 'error', <?php echo wp_json_encode( __( 'Please select a .zip file.', 'seedcast-sermon-library' ) ); ?> );
					return;
				}
				zipFile = file;
				uploadAndPreview( file );
			}

			function uploadAndPreview( file ) {
				var fd = new FormData();
				fd.append( 'action', 'scsl_import_manifest' );
				fd.append( 'nonce', nonce );
				fd.append( 'post_id', postId );
				fd.append( 'phase', 'preview' );
				fd.append( 'zip', file );

				showResult( 'info', <?php echo wp_json_encode( __( 'Reading manifest…', 'seedcast-sermon-library' ) ); ?> );
				$preview.hide();

				$.ajax( {
					url: ajaxurl,
					type: 'POST',
					data: fd,
					processData: false,
					contentType: false,
					success: function( res ) {
						if ( ! res.success ) {
							showResult( 'error', res.data );
							return;
						}
						manifest = res.data;
						renderPreview( manifest );
						$result.hide();
					},
					error: function() {
						showResult( 'error', <?php echo wp_json_encode( __( 'Upload failed. Please try again.', 'seedcast-sermon-library' ) ); ?> );
					}
				} );
			}

			function renderPreview( data ) {
				$( '#scsl-manifest-title' ).text( data.meta.title || '' );
				$( '#scsl-manifest-scripture' ).text( data.meta.primary_scripture || '' ).toggle( !! data.meta.primary_scripture );
				$( '#scsl-manifest-speaker' ).text( data.meta.speaker || '' ).toggle( !! data.meta.speaker );

				var $list = $( '#scsl-manifest-items' ).empty();
				$.each( data.items, function( key, item ) {
					$list.append(
						$( '<li>' ).append(
							$( '<input type="checkbox" checked />' ).attr( 'data-key', key ),
							$( '<span>' ).text( item.label )
						)
					);
				} );

				$preview.show();
			}

			$( '#scsl-manifest-import-btn' ).on( 'click', function() {
				var selected = [];
				$( '#scsl-manifest-items input:checked' ).each( function() {
					selected.push( $( this ).data( 'key' ) );
				} );

				if ( ! selected.length ) {
					showResult( 'error', <?php echo wp_json_encode( __( 'Select at least one item to import.', 'seedcast-sermon-library' ) ); ?> );
					return;
				}

				var fd = new FormData();
				fd.append( 'action', 'scsl_import_manifest' );
				fd.append( 'nonce', nonce );
				fd.append( 'post_id', postId );
				fd.append( 'phase', 'import' );
				fd.append( 'zip', zipFile );
				fd.append( 'selected', JSON.stringify( selected ) );
				fd.append( 'overwrite', $( '#scsl-manifest-overwrite' ).is( ':checked' ) ? '1' : '0' );

				$( this ).prop( 'disabled', true ).text( <?php echo wp_json_encode( __( 'Importing…', 'seedcast-sermon-library' ) ); ?> );

				$.ajax( {
					url: ajaxurl,
					type: 'POST',
					data: fd,
					processData: false,
					contentType: false,
					success: function( res ) {
						$( '#scsl-manifest-import-btn' ).prop( 'disabled', false ).text( <?php echo wp_json_encode( __( 'Import Content', 'seedcast-sermon-library' ) ); ?> );
						if ( res.success ) {
							showResult( 'success', res.data.message );
							$preview.hide();
							$area.hide();
							// Reload to show populated fields
							setTimeout( function() { location.reload(); }, 1200 );
						} else {
							showResult( 'error', res.data );
						}
					},
					error: function() {
						$( '#scsl-manifest-import-btn' ).prop( 'disabled', false ).text( <?php echo wp_json_encode( __( 'Import Content', 'seedcast-sermon-library' ) ); ?> );
						showResult( 'error', <?php echo wp_json_encode( __( 'Import failed. Please try again.', 'seedcast-sermon-library' ) ); ?> );
					}
				} );
			} );

			$( '#scsl-manifest-cancel-btn' ).on( 'click', function() {
				$preview.hide();
				$result.hide();
				zipFile = null;
				manifest = null;
				$input.val( '' );
			} );

			function showResult( type, message ) {
				var cls = type === 'success' ? 'notice-success' : ( type === 'error' ? 'notice-error' : 'notice-info' );
				$result.html( '<div class="notice ' + cls + ' inline"><p>' + $( '<span>' ).text( message ).html() + '</p></div>' ).show();
			}

		} );
		</script>
		<?php
	}

	public function handle_upload(): void {
		$post_id = isset( $_POST['post_id'] ) ? absint( $_POST['post_id'] ) : 0;
		$phase   = isset( $_POST['phase'] ) ? sanitize_key( $_POST['phase'] ) : '';

		if ( ! $post_id || ! check_ajax_referer( 'scsl_import_manifest_' . $post_id, 'nonce', false ) ) {
			wp_send_json_error( __( 'Security check failed.', 'seedcast-sermon-library' ) );
		}

		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			wp_send_json_error( __( 'You do not have permission to edit this post.', 'seedcast-sermon-library' ) );
		}

		if ( empty( $_FILES['zip']['tmp_name'] ) ) {
			wp_send_json_error( __( 'No file received.', 'seedcast-sermon-library' ) );
		}

		// Validate it's a zip
		$file     = $_FILES['zip']; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput
		$tmp_path = $file['tmp_name'];
		$finfo    = new \finfo( FILEINFO_MIME_TYPE );
		$mime     = $finfo->file( $tmp_path );

		if ( ! in_array( $mime, [ 'application/zip', 'application/x-zip-compressed', 'application/octet-stream' ], true ) ) {
			wp_send_json_error( __( 'File must be a .zip archive.', 'seedcast-sermon-library' ) );
		}

		// Extract to temp dir
		$extract_dir = get_temp_dir() . 'scsl_manifest_' . $post_id . '_' . wp_generate_password( 8, false ) . '/';
		wp_mkdir_p( $extract_dir );

		$zip = new \ZipArchive();
		if ( $zip->open( $tmp_path ) !== true ) {
			$this->cleanup( $extract_dir );
			wp_send_json_error( __( 'Could not open zip file.', 'seedcast-sermon-library' ) );
		}
		$zip->extractTo( $extract_dir );
		$zip->close();

		// Find manifest.xml
		$manifest_path = $extract_dir . 'manifest.xml';
		if ( ! file_exists( $manifest_path ) ) {
			$this->cleanup( $extract_dir );
			wp_send_json_error( __( 'No manifest.xml found in zip.', 'seedcast-sermon-library' ) );
		}

		$manifest = $this->parse_manifest( $manifest_path, $extract_dir );
		if ( is_wp_error( $manifest ) ) {
			$this->cleanup( $extract_dir );
			wp_send_json_error( $manifest->get_error_message() );
		}

		if ( $phase === 'preview' ) {
			$this->cleanup( $extract_dir );
			wp_send_json_success( $manifest );
		}

		// Import phase
		$selected  = isset( $_POST['selected'] ) ? json_decode( sanitize_text_field( wp_unslash( $_POST['selected'] ) ), true ) : [];
		$overwrite = ! empty( $_POST['overwrite'] ) && $_POST['overwrite'] === '1';

		if ( ! is_array( $selected ) ) {
			$this->cleanup( $extract_dir );
			wp_send_json_error( __( 'Invalid selection.', 'seedcast-sermon-library' ) );
		}

		$result = $this->import( $post_id, $manifest, $selected, $overwrite );
		$this->cleanup( $extract_dir );

		if ( is_wp_error( $result ) ) {
			wp_send_json_error( $result->get_error_message() );
		}

		wp_send_json_success( [
			'message' => sprintf(
				/* translators: %d number of fields imported */
				__( 'Imported %d fields successfully.', 'seedcast-sermon-library' ),
				$result
			),
		] );
	}

	/**
	 * Parse manifest.xml and load file contents.
	 *
	 * @return array|\WP_Error
	 */
	private function parse_manifest( string $manifest_path, string $extract_dir ) {
		libxml_use_internal_errors( true );
		$xml = simplexml_load_file( $manifest_path );
		if ( ! $xml ) {
			return new \WP_Error( 'bad_xml', __( 'Could not parse manifest.xml.', 'seedcast-sermon-library' ) );
		}

		$meta = [];
		foreach ( $xml->meta->field as $field ) {
			$name        = (string) $field['name'];
			$meta[ $name ] = (string) $field;
		}

		$items = [];
		foreach ( $xml->items->item as $item ) {
			$key      = (string) $item['key'];
			$label    = (string) $item['label'];
			$file     = (string) $item['file'];
			$filepath = $extract_dir . $file;

			if ( file_exists( $filepath ) ) {
				$items[ $key ] = [
					'label'   => $label,
					'content' => $this->read_file( $filepath ),
				];
			}
		}

		return [
			'meta'  => $meta,
			'items' => $items,
		];
	}

	/**
	 * Write manifest data to sermon post meta.
	 *
	 * @return int|\WP_Error Number of fields written.
	 */
	private function import( int $post_id, array $manifest, array $selected, bool $overwrite ) {
		$meta  = $manifest['meta'];
		$items = $manifest['items'];
		$count = 0;

		// Helper: only write if overwrite=true or field is empty
		$write = function( string $key, $value ) use ( $post_id, $overwrite, &$count ) {
			if ( ! $overwrite ) {
				$existing = get_post_meta( $post_id, $key, true );
				if ( ! empty( $existing ) ) return;
			}
			update_post_meta( $post_id, $key, $value );
			$count++;
		};

		// Post title from meta
		if ( ! empty( $meta['title'] ) ) {
			$existing_title = get_post_field( 'post_title', $post_id );
			if ( $overwrite || empty( $existing_title ) || $existing_title === __( 'Auto Draft', 'seedcast-sermon-library' ) ) {
				wp_update_post( [
					'ID'         => $post_id,
					'post_title' => sanitize_text_field( $meta['title'] ),
				] );
				$count++;
			}
		}

		// Primary scripture → focus passage
		if ( ! empty( $meta['primary_scripture'] ) ) {
			$write( '_scsl_focus_passage', sanitize_text_field( $meta['primary_scripture'] ) );
		}

		// Speaker → look up by name
		if ( ! empty( $meta['speaker'] ) ) {
			$speaker = get_posts( [
				'post_type'      => 'scsl_speaker',
				'title'          => $meta['speaker'],
				'posts_per_page' => 1,
				'post_status'    => 'publish',
				'fields'         => 'ids',
			] );
			if ( ! empty( $speaker ) ) {
				$write( '_scsl_speaker_id', absint( $speaker[0] ) );
			}
		}

		// Read from the shared map rather than a local copy. The AI Engine
		// imports the same content from the API and reads the same map, so
		// the two paths cannot produce different sermons from the same
		// generation.
		$key_map = FieldMap::api_to_meta();

		foreach ( $selected as $item_key ) {
			if ( ! isset( $items[ $item_key ] ) ) continue;
			$content = $items[ $item_key ]['content'];

			if ( isset( $key_map[ $item_key ] ) ) {
				$meta_key = $key_map[ $item_key ];
				if ( in_array( $meta_key, FieldMap::plain_text_meta(), true ) ) {
					// Plain text fields: strip tags
					$write( $meta_key, sanitize_textarea_field( wp_strip_all_tags( $content ) ) );
				} else {
					// Rich HTML fields
					$write( $meta_key, wp_kses_post( $content ) );
				}

				// Extract article title from first h2/h3 in article
				if ( $item_key === 'article' ) {
					preg_match( '/<h[23][^>]*>(.*?)<\/h[23]>/i', $content, $heading );
					if ( ! empty( $heading[1] ) ) {
						$write( '_scsl_article_title', sanitize_text_field( wp_strip_all_tags( $heading[1] ) ) );
					}
				}
			}

			// scripture.html → other passages
			if ( $item_key === 'scripture' ) {
				preg_match_all( '/<li>(.*?)<\/li>/i', $content, $matches );
				$passages = [];
				foreach ( $matches[1] as $passage ) {
					$clean = sanitize_text_field( wp_strip_all_tags( $passage ) );
					// Strip "Main: " prefix: that's the focus passage
					$clean = preg_replace( '/^Main:\s*/i', '', $clean );
					if ( $clean ) $passages[] = $clean;
				}
				if ( $passages ) {
					if ( ! $overwrite ) {
						$existing = get_post_meta( $post_id, '_scsl_other_passages', true );
						if ( empty( $existing ) ) {
							update_post_meta( $post_id, '_scsl_other_passages', $passages );
						SermonMeta::sync_scripture( $post_id );
							$count++;
						}
					} else {
						update_post_meta( $post_id, '_scsl_other_passages', $passages );
						SermonMeta::sync_scripture( $post_id );
						$count++;
					}
				}
			}

			// Several fields stack into the single resources body.
			if ( in_array( $item_key, FieldMap::appended_fields(), true ) ) {
				$existing_resources = get_post_meta( $post_id, '_scsl_resources', true ) ?: '';
				$label   = $items[ $item_key ]['label'];
				$section = '<h3>' . esc_html( $label ) . '</h3>' . wp_kses_post( $content );
				if ( $overwrite || strpos( $existing_resources, $label ) === false ) {
					update_post_meta( $post_id, '_scsl_resources', $existing_resources . $section );
					$count++;
				}
			}
		}

		return $count;
	}

	/**
	 * WP_Filesystem, initialised on first use.
	 *
	 * Reading and deleting go through it rather than PHP's own functions so
	 * this works on hosts where WordPress writes over FTP or SSH instead of
	 * touching the disk as the web user.
	 *
	 * @return \WP_Filesystem_Base|null
	 */
	private function filesystem() {
		global $wp_filesystem;

		if ( ! $wp_filesystem ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
			WP_Filesystem();
		}

		return $wp_filesystem ?: null;
	}

	/**
	 * Read one extracted file.
	 *
	 * @param string $filepath Absolute path inside the extraction directory.
	 * @return string Empty string when the file cannot be read.
	 */
	private function read_file( string $filepath ): string {
		$fs = $this->filesystem();
		if ( ! $fs ) {
			return '';
		}

		$contents = $fs->get_contents( $filepath );

		return false === $contents ? '' : (string) $contents;
	}

	/**
	 * Remove the temporary extraction directory.
	 *
	 * Goes through WP_Filesystem rather than calling rmdir() directly, so it
	 * works on hosts where WordPress writes over FTP or SSH instead of
	 * touching the disk as the web user.
	 */
	private function cleanup( string $dir ): void {
		if ( ! is_dir( $dir ) ) return;

		$fs = $this->filesystem();

		if ( $fs ) {
			// Recursive delete, which handles the files inside as well.
			$fs->delete( $dir, true );
			return;
		}

		// WP_Filesystem could not be initialised, which happens when
		// credentials are needed and none are available. Fall back to removing
		// the files we can, so a temp directory full of an uploaded zip is not
		// left behind.
		$files = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \RecursiveDirectoryIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ( $files as $file ) {
			if ( ! $file->isDir() ) {
				wp_delete_file( $file->getRealPath() );
			}
		}
	}
}
